import Image from 'next/image'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import NavBar from '@/components/commons/navbar'
import Drawer from '@/components/commons/drawer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Drawer />
    </div>
  )
}
